# Generated by Django 2.2 on 2021-10-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211019_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_comment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mycomments', to='posts.Comment'),
            preserve_default=False,
        ),
    ]
