# Generated by Django 2.2 on 2021-10-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mycomments', to='posts.Comment'),
        ),
    ]
