# Generated by Django 2.2 on 2021-10-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211023_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_comment',
        ),
    ]
